version: '3.8'
services:
  db:
    image: postgres:18-alpine3.22
    container_name: student-competitions-db
    environment:
      POSTGRES_DB: student_competitions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - student_competitions_data:/var/lib/postgresql/data
    networks:
      - student-network

  api:
    image: aslelin/student-competitions-api:1.0.0
    container_name: student-competitions-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: student_competitions
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - student-network

  front:
    image: aslelin/student-competitions-client:1.0.0
    container_name: student-competitions-front
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - student-network

volumes:
  student_competitions_data:

networks:
  student-network:
    driver: bridge