version: '3.8'
services:
  db:
    image: postgres:18-alpine3.22
    container_name: student-competitions-db
    environment:
      POSTGRES_DB: student_competitions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - student_competitions_data:/var/lib/postgresql/data
    networks:
      - student-network

  app:
    image: aslelin/student-competitions-api:1.0.0
    container_name: student-competitions-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/student_competitions
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - student-network

volumes:
  student_competitions_data:

networks:
  student-network:
    driver: bridge